# Generated by Django 5.2.7 on 2026-02-13 01:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description détaillée')),
                ('listing_type', models.CharField(choices=[('LOCATION', 'Location'), ('VENTE', 'Vente')], max_length=16, verbose_name='Type')),
                ('status', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif')], default='ACTIF', max_length=16, verbose_name='Statut')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('neighborhood', models.CharField(blank=True, max_length=100, verbose_name='Quartier')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix affiché (XOF)')),
                ('rooms', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Nombre de pièces')),
                ('bedrooms', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Chambres')),
                ('bathrooms', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Salles de bain')),
                ('surface_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Surface (m²)')),
                ('furnishing', models.CharField(blank=True, choices=[('FURNISHED', 'Meublé'), ('UNFURNISHED', 'Non meublé'), ('SEMI_FURNISHED', 'Semi-meublé')], max_length=16, verbose_name='Ameublement')),
                ('amenities', models.JSONField(blank=True, default=list, help_text='Liste de commodités : eau, electricite, parking, gardien, etc.', verbose_name='Commodités')),
                ('views_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Nombre de vues')),
                ('favorites_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Favoris')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(limit_choices_to={'role': 'AGENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listings/images/')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Légende')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.listing')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='listings/videos/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='listings/thumbnails/')),
                ('duration_sec', models.PositiveIntegerField(blank=True, null=True, verbose_name='Durée (s)')),
                ('access_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('views_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Vues')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='listings.listing')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['agent', '-created_at'], name='idx_listing_agent_date'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['city', 'listing_type', 'status'], name='idx_listing_search'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status', '-created_at'], name='idx_listing_active'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status', 'listing_type', 'price'], name='idx_listing_price'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['listing', '-created_at'], name='idx_video_listing_date'),
        ),
    ]
