# Generated by Django 5.2.7 on 2026-02-17 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('ALREADY_SOLD', 'Bien déjà vendu'), ('ALREADY_RENTED', 'Bien déjà loué'), ('MISLEADING', 'Annonce trompeuse / vidéo ne correspond pas'), ('DUPLICATE_VIDEO', 'Même vidéo que sur une autre annonce'), ('SCAM', 'Arnaque suspectée'), ('OTHER', 'Autre')], max_length=24, verbose_name='Raison')),
                ('description', models.TextField(blank=True, help_text='Explication facultative du signalement.', verbose_name='Détails')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('REVIEWED', 'Examiné'), ('RESOLVED', 'Résolu (annonce supprimée/suspendue)'), ('DISMISSED', 'Rejeté (faux signalement)')], default='PENDING', max_length=16, verbose_name='Statut')),
                ('admin_note', models.TextField(blank=True, verbose_name='Note admin')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Examiné le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text="Date d'expiration automatique.", null=True, verbose_name='Expire le'),
        ),
        migrations.AddField(
            model_name='listing',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='Date de la dernière publication/renouvellement.', null=True, verbose_name='Publié le'),
        ),
        migrations.AddField(
            model_name='listing',
            name='reports_count',
            field=models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='Signalements'),
        ),
        migrations.AddField(
            model_name='video',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, help_text="SHA-256 du fichier vidéo, calculé à l'upload pour détection de doublons.", max_length=64, verbose_name='Hash SHA-256'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('EXPIRED', 'Expirée'), ('SUSPENDED', 'Suspendue')], default='ACTIF', max_length=16, verbose_name='Statut'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status', 'expires_at'], name='idx_listing_expiry'),
        ),
        migrations.AddField(
            model_name='listingreport',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='listings.listing'),
        ),
        migrations.AddField(
            model_name='listingreport',
            name='user',
            field=models.ForeignKey(help_text='Client qui signale', limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='listing_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='listingreport',
            index=models.Index(fields=['listing', 'status'], name='idx_report_listing_status'),
        ),
        migrations.AddIndex(
            model_name='listingreport',
            index=models.Index(fields=['status', '-created_at'], name='idx_report_pending'),
        ),
        migrations.AddConstraint(
            model_name='listingreport',
            constraint=models.UniqueConstraint(fields=('user', 'listing'), name='unique_user_listing_report'),
        ),
    ]
