# Generated by Django 5.2.7 on 2026-02-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listingreport_listing_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='advance_months',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Nombre de mois d'avance exigés.", null=True, verbose_name='Avance (mois)'),
        ),
        migrations.AddField(
            model_name='listing',
            name='agency_fee_months',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Nombre de mois de frais d'agence.", null=True, verbose_name="Frais d'agence (mois)"),
        ),
        migrations.AddField(
            model_name='listing',
            name='deposit_months',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Nombre de mois de caution exigés.', null=True, verbose_name='Caution (mois)'),
        ),
        migrations.AddField(
            model_name='listing',
            name='other_conditions',
            field=models.TextField(blank=True, help_text='Conditions supplémentaires en texte libre.', verbose_name='Autres conditions'),
        ),
    ]
