# Generated by Django 5.2.7 on 2026-02-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_add_acquisition_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='perceptual_hash',
            field=models.CharField(blank=True, db_index=True, help_text='Hash perceptuel 64-bit (hex) via VideoHash — détection de copies visuellement similaires.', max_length=16, verbose_name='Hash perceptuel'),
        ),
        migrations.AlterField(
            model_name='video',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-256 du fichier vidéo — détection de doublons exacts.', max_length=64, verbose_name='Hash SHA-256'),
        ),
    ]
