# Generated by Django 5.2.7 on 2026-02-28 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_add_perceptual_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Supprimé le'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('EXPIRED', 'Expirée'), ('SUSPENDED', 'Suspendue'), ('DELETED', 'Supprimée')], default='ACTIF', max_length=16, verbose_name='Statut'),
        ),
    ]
