# Generated by Django 5.2.7 on 2026-04-01 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_protect_monetization_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='agent_note',
            field=models.TextField(blank=True, help_text="Notes internes de l'agent (non visible par les clients).", verbose_name='Note privée'),
        ),
    ]
