# Generated by Django 5.2.7 on 2026-04-01 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_add_agent_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='perceptual_hash',
            field=models.CharField(blank=True, db_index=True, help_text='Hash perceptuel 64-bit (hex) via VideoHash — détection de copies visuellement similaires.', max_length=18, verbose_name='Hash perceptuel'),
        ),
    ]
