# Generated by Django 5.2.7 on 2026-04-01 14:23

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    """Génère un slug unique pour chaque listing existant."""
    Listing = apps.get_model('listings', 'Listing')
    seen_slugs = set()
    for listing in Listing.objects.all().order_by('id'):
        base = slugify(f"{listing.title} {listing.city}")[:250] or 'annonce'
        slug = base
        counter = 1
        while slug in seen_slugs:
            slug = f"{base}-{counter}"
            counter += 1
        seen_slugs.add(slug)
        listing.slug = slug
        listing.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_increase_perceptual_hash_maxlength'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='slug',
            field=models.SlugField(
                blank=True, default='',
                help_text='Généré automatiquement depuis le titre et la ville.',
                max_length=280, verbose_name='Slug',
                db_index=False,
            ),
            preserve_default=False,
        ),
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
        migrations.RunSQL(
            sql='DROP INDEX IF EXISTS listings_listing_slug_984b866c_like;',
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='listing',
            name='slug',
            field=models.SlugField(
                blank=True, unique=True,
                help_text='Généré automatiquement depuis le titre et la ville.',
                max_length=280, verbose_name='Slug',
            ),
        ),
    ]
