# Generated by Django 5.2.7 on 2026-04-10 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_add_slug_to_listing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='visits_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Visites'),
        ),
        migrations.CreateModel(
            name='ListingVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_visits', to='listings.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['listing', '-created_at'], name='idx_listing_visit_date')],
                'constraints': [models.UniqueConstraint(fields=('listing', 'user'), name='unique_listing_visit_per_user')],
            },
        ),
    ]
