# Generated by Django 5.2.7 on 2025-11-04 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_external_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_provider',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
