# Generated by Django 5.2.7 on 2025-11-05 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_otp_external_id_user_otp_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp_expires_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp_external_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp_provider',
        ),
    ]
