# Generated by Django 5.2.7 on 2025-11-08 18:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_otp_code_remove_user_otp_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=32, unique=True, validators=[django.core.validators.RegexValidator(message='Le numéro doit être au format E.164 (ex: +2250123456789)', regex='^\\+[1-9]\\d{5,14}$')]),
        ),
    ]
