# Generated by Django 5.2.7 on 2026-02-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentdocument',
            name='doc_type',
            field=models.CharField(choices=[('CNI', "Carte Nationale d'Identité"), ('PASSPORT', 'Passeport'), ('PERMIT', 'Permis de conduire'), ('OTHER', 'Autre')], default='CNI', max_length=16),
        ),
        migrations.AddField(
            model_name='agentdocument',
            name='side',
            field=models.CharField(choices=[('RECTO', 'Recto'), ('VERSO', 'Verso'), ('SINGLE', 'Document unique')], default='SINGLE', max_length=8),
        ),
        migrations.AddField(
            model_name='agentdocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='agentdocument',
            unique_together={('agent_profile', 'doc_type', 'side')},
        ),
    ]
