# Generated by Django 5.2.7 on 2026-02-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_kyc_document_type_side'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='kyc_rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='kyc_status',
            field=models.CharField(choices=[('NOT_SUBMITTED', 'Non soumis'), ('PENDING', 'En attente de vérification'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté')], default='NOT_SUBMITTED', max_length=16),
        ),
    ]
