# Generated by Django 5.2.7 on 2026-02-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_kyc_status_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, help_text='Route frontend (ex: /agent/visits, /agent/settings#kyc)', max_length=255, verbose_name='Lien de navigation'),
        ),
    ]
