# Generated by Django 5.2.7 on 2026-03-31 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_notification_add_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('CGU', "Conditions Générales d'Utilisation"), ('PRIVACY', 'Politique de Confidentialité'), ('AGENT_CONDITIONS', 'Conditions Spécifiques Agents')], max_length=32)),
                ('document_version', models.CharField(max_length=32)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-accepted_at'],
                'indexes': [models.Index(fields=['user', 'document_type'], name='users_legal_user_id_d6bc44_idx')],
            },
        ),
    ]
