# Generated by Django 5.2.7 on 2026-04-01 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_legalconsent'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='is_partner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='partner_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
