# Generated by Django 5.2.7 on 2025-11-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmsDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(blank=True, max_length=128)),
                ('address', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(blank=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['message_id'], name='core_smsdel_message_2c59a3_idx'), models.Index(fields=['address'], name='core_smsdel_address_380a2d_idx'), models.Index(fields=['status'], name='core_smsdel_status_d3104a_idx')],
            },
        ),
    ]
