# Generated by Django 5.2.7 on 2026-02-13 01:33

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('500.00'), max_digits=10, verbose_name='Montant')),
                ('currency', models.CharField(default='XOF', max_length=3, verbose_name='Devise')),
                ('virtual_total', models.PositiveSmallIntegerField(default=33, verbose_name='Clés virtuelles totales')),
                ('virtual_used', models.PositiveSmallIntegerField(default=0, verbose_name='Clés virtuelles utilisées')),
                ('has_physical_key', models.BooleanField(default=True, verbose_name='Clé physique disponible')),
                ('is_locked_by_visit', models.BooleanField(default=False, help_text="True dès qu'une visite physique consomme la clé physique.", verbose_name='Pack verrouillé par visite')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='packs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VirtualKeyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_agent', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=10, verbose_name='Revenu agent')),
                ('amount_platform', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=10, verbose_name='Revenu plateforme')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(help_text="Agent propriétaire de l'annonce (bénéficiaire)", on_delete=django.db.models.deletion.CASCADE, related_name='earned_views', to=settings.AUTH_USER_MODEL)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_usages', to='packs.packpurchase')),
                ('user', models.ForeignKey(help_text='Client qui a visionné', on_delete=django.db.models.deletion.CASCADE, related_name='video_views', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_usages', to='listings.video')),
            ],
        ),
        migrations.AddIndex(
            model_name='packpurchase',
            index=models.Index(fields=['user', 'is_locked_by_visit', '-created_at'], name='idx_pack_user_active'),
        ),
        migrations.AddIndex(
            model_name='virtualkeyusage',
            index=models.Index(fields=['user', 'video'], name='idx_usage_user_video'),
        ),
        migrations.AddIndex(
            model_name='virtualkeyusage',
            index=models.Index(fields=['agent', '-created_at'], name='idx_usage_agent_date'),
        ),
        migrations.AddIndex(
            model_name='virtualkeyusage',
            index=models.Index(fields=['video', '-created_at'], name='idx_usage_video_date'),
        ),
        migrations.AddConstraint(
            model_name='virtualkeyusage',
            constraint=models.UniqueConstraint(fields=('pack', 'video', 'user'), name='unique_pack_video_user'),
        ),
    ]
