# Generated by Django 5.2.7 on 2026-02-28 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_protect_monetization_data'),
        ('packs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='virtualkeyusage',
            name='unique_pack_video_user',
        ),
        migrations.AlterField(
            model_name='virtualkeyusage',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='key_usages', to='listings.video'),
        ),
        migrations.AddConstraint(
            model_name='virtualkeyusage',
            constraint=models.UniqueConstraint(condition=models.Q(('video__isnull', False)), fields=('pack', 'video', 'user'), name='unique_pack_video_user'),
        ),
    ]
