# Generated by Django 5.2.7 on 2026-02-13 01:33

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=10, verbose_name='Montant')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='platform_revenue', to='packs.virtualkeyusage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Solde (XOF)')),
                ('total_earned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cumul historique de tous les crédits.', max_digits=12, verbose_name='Total gagné (XOF)')),
                ('total_withdrawn', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total retiré (XOF)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.OneToOneField(limit_choices_to={'role': 'AGENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WalletEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('CREDIT', 'Crédit (gain)'), ('DEBIT', 'Débit (retrait)')], max_length=8, verbose_name='Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('label', models.CharField(blank=True, max_length=255, verbose_name='Libellé')),
                ('withdrawal_method', models.CharField(blank=True, help_text='Ex: ORANGE_MONEY, WAVE, MTN', max_length=32, verbose_name='Méthode de retrait')),
                ('withdrawal_ref', models.CharField(blank=True, max_length=128, verbose_name='Référence retrait')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ref_usage', models.OneToOneField(blank=True, help_text='VirtualKeyUsage ayant généré ce crédit (si applicable).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_entry', to='packs.virtualkeyusage')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='wallet.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['wallet', '-created_at'], name='idx_entry_wallet_date')],
            },
        ),
    ]
