# Generated by Django 5.2.7 on 2026-02-17 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0001_initial'),
        ('visits', '0004_alter_visitrequest_response_deadline_and_more'),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformrevenue',
            name='source',
            field=models.CharField(choices=[('VIDEO_VIEW', 'Visionnage vidéo'), ('PHYSICAL_VISIT', 'Visite physique')], default='VIDEO_VIEW', max_length=20, verbose_name='Source'),
        ),
        migrations.AddField(
            model_name='platformrevenue',
            name='visit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platform_revenue', to='visits.visitrequest'),
        ),
        migrations.AddField(
            model_name='walletentry',
            name='ref_visit',
            field=models.OneToOneField(blank=True, help_text='VisitRequest ayant généré ce crédit.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_entry', to='visits.visitrequest'),
        ),
        migrations.AddField(
            model_name='walletentry',
            name='source',
            field=models.CharField(choices=[('VIDEO_VIEW', 'Visionnage vidéo'), ('PHYSICAL_VISIT', 'Visite physique'), ('WITHDRAWAL', 'Retrait'), ('ADJUSTMENT', 'Ajustement admin')], default='VIDEO_VIEW', max_length=20, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='platformrevenue',
            name='usage',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platform_revenue', to='packs.virtualkeyusage'),
        ),
        migrations.AlterField(
            model_name='walletentry',
            name='ref_usage',
            field=models.OneToOneField(blank=True, help_text='VirtualKeyUsage ayant généré ce crédit.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_entry', to='packs.virtualkeyusage'),
        ),
    ]
