# Generated by Django 5.2.7 on 2026-02-17 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0005_visitrequest_virtual_key_consumed'),
        ('wallet', '0002_platformrevenue_source_platformrevenue_visit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformrevenue',
            name='visit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_revenue', to='visits.visitrequest'),
        ),
    ]
