# Generated by Django 5.2.7 on 2026-02-17 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_platformrevenue_visit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant (XOF)')),
                ('method', models.CharField(choices=[('ORANGE_MONEY', 'Orange Money'), ('WAVE', 'Wave'), ('MTN', 'MTN Mobile Money')], max_length=16, verbose_name='Méthode')),
                ('phone_number', models.CharField(help_text='Numéro mobile money pour le virement.', max_length=20, verbose_name='Numéro de destination')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('COMPLETED', 'Effectué'), ('REJECTED', 'Rejeté')], default='PENDING', max_length=12, verbose_name='Statut')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Traité le')),
                ('admin_note', models.TextField(blank=True, verbose_name='Note admin')),
                ('transaction_ref', models.CharField(blank=True, help_text='Référence de la transaction mobile money.', max_length=128, verbose_name='Réf. transaction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_by', models.ForeignKey(blank=True, help_text='Admin ayant traité la demande.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='wallet.wallet')),
                ('wallet_entry', models.OneToOneField(blank=True, help_text='Entrée DEBIT créée lors de la demande.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_request', to='wallet.walletentry')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['wallet', 'status', '-created_at'], name='idx_withdrawal_wallet'), models.Index(fields=['status', '-created_at'], name='idx_withdrawal_status')],
            },
        ),
    ]
