# Generated by Django 5.2.7 on 2026-02-17 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_withdrawalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='withdrawal_pin_hash',
            field=models.CharField(blank=True, help_text='Code PIN à 4 chiffres, hashé via make_password. Requis pour chaque demande de retrait.', max_length=128, verbose_name='PIN de retrait (hashé)'),
        ),
    ]
