# Generated by Django 5.2.7 on 2026-02-28 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0002_protect_monetization_data'),
        ('wallet', '0005_wallet_withdrawal_pin_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformrevenue',
            name='usage',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_revenue', to='packs.virtualkeyusage'),
        ),
    ]
