# Generated by Django 5.2.7 on 2026-02-13 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        ('packs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REQUESTED', 'Demandée'), ('CONFIRMED', 'Confirmée'), ('DONE', 'Effectuée'), ('NO_SHOW', 'Absent'), ('CANCELED', 'Annulée')], default='REQUESTED', max_length=16, verbose_name='Statut')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Date prévue')),
                ('consumed_physical_key_at', models.DateTimeField(blank=True, null=True, verbose_name='Clé physique consommée le')),
                ('client_note', models.TextField(blank=True, verbose_name='Note du client')),
                ('agent_note', models.TextField(blank=True, verbose_name="Note de l'agent")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_requests', to='listings.listing')),
                ('pack', models.OneToOneField(help_text='Pack dont la clé physique est consommée (1 visite max par pack).', on_delete=django.db.models.deletion.CASCADE, related_name='visit_request', to='packs.packpurchase')),
                ('user', models.ForeignKey(help_text='Client demandeur', limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='visit_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['listing', 'status'], name='idx_visit_listing_status'), models.Index(fields=['user', '-created_at'], name='idx_visit_user_date')],
            },
        ),
    ]
