# Generated by Django 5.2.7 on 2026-02-17 18:23

import apps.visits.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listingreport_listing_expires_at_and_more'),
        ('packs', '0001_initial'),
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='visitrequest',
            name='code_validated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Code validé le'),
        ),
        migrations.AddField(
            model_name='visitrequest',
            name='response_deadline',
            field=models.DateTimeField(blank=True, help_text="L'agent doit confirmer ou refuser avant cette date, sinon la visite expire et la clé physique est restaurée.", null=True, verbose_name='Délai de réponse agent'),
        ),
        migrations.AddField(
            model_name='visitrequest',
            name='verification_code',
            field=models.CharField(default=apps.visits.models._generate_visit_code, help_text="Code 6 chiffres que le client donne à l'agent lors de la visite.", max_length=6, verbose_name='Code de vérification'),
        ),
        migrations.AlterField(
            model_name='visitrequest',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Demandée'), ('CONFIRMED', "Confirmée par l'agent"), ('DONE', 'Effectuée (code validé)'), ('NO_SHOW', 'Absent'), ('CANCELED', 'Annulée par le client'), ('EXPIRED', "Expirée (agent n'a pas répondu)")], default='REQUESTED', max_length=16, verbose_name='Statut'),
        ),
        migrations.AddIndex(
            model_name='visitrequest',
            index=models.Index(fields=['status', 'response_deadline'], name='idx_visit_deadline'),
        ),
    ]
