# Generated by Django 5.2.7 on 2026-02-17 19:04

import apps.visits.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_visitrequest_code_validated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitrequest',
            name='verification_code',
            field=models.CharField(default=apps.visits.models._generate_visit_code, help_text="Code 5 caractères alphanumériques (ex: A3K7F) communiqué par le client à l'agent.", max_length=5, verbose_name='Code de vérification'),
        ),
    ]
