# Generated by Django 5.2.7 on 2026-02-17 19:38

import apps.visits.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0003_alter_visitrequest_verification_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitrequest',
            name='response_deadline',
            field=models.DateTimeField(blank=True, help_text="L'agent doit confirmer avant cette date, sinon la visite expire et les clés sont restaurées.", null=True, verbose_name='Délai de réponse agent'),
        ),
        migrations.AlterField(
            model_name='visitrequest',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, help_text='Date/heure concrète de la visite (calculée à partir du créneau).', null=True, verbose_name='Date prévue'),
        ),
        migrations.AlterField(
            model_name='visitrequest',
            name='verification_code',
            field=models.CharField(default=apps.visits.models._generate_visit_code, help_text="Code 5 caractères alphanumériques (ex: A3K7F) — l'agent le demande au client AVANT de commencer la visite.", max_length=5, verbose_name='Code de vérification'),
        ),
        migrations.CreateModel(
            name='AgentAvailabilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], verbose_name='Jour de la semaine')),
                ('start_time', models.TimeField(verbose_name='Début')),
                ('end_time', models.TimeField(verbose_name='Fin')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(limit_choices_to={'role': 'AGENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='visitrequest',
            name='slot',
            field=models.ForeignKey(blank=True, help_text='Créneau choisi par le client.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_requests', to='visits.agentavailabilityslot'),
        ),
        migrations.AddIndex(
            model_name='agentavailabilityslot',
            index=models.Index(fields=['agent', 'day_of_week', 'is_active'], name='idx_slot_agent_day'),
        ),
    ]
