# Generated by Django 5.2.7 on 2026-02-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0004_alter_visitrequest_response_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitrequest',
            name='virtual_key_consumed',
            field=models.BooleanField(default=False, help_text="True si une clé virtuelle a été consommée (client n'avait pas encore vu la vidéo).", verbose_name='Clé virtuelle consommée'),
        ),
    ]
