# Generated by Django 5.2.7 on 2026-02-28 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0006_agentdateslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitrequest',
            name='meeting_address',
            field=models.CharField(blank=True, help_text='Description textuelle du point de rencontre (ex: « Devant la pharmacie »).', max_length=255, verbose_name='Lieu de rendez-vous'),
        ),
        migrations.AddField(
            model_name='visitrequest',
            name='meeting_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude RDV'),
        ),
        migrations.AddField(
            model_name='visitrequest',
            name='meeting_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude RDV'),
        ),
    ]
