# Generated by Django 5.2.7 on 2026-02-28 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0001_initial'),
        ('visits', '0007_add_meeting_location_to_visitrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitrequest',
            name='cancel_reason',
            field=models.TextField(blank=True, verbose_name="Motif d'annulation"),
        ),
        migrations.AlterField(
            model_name='visitrequest',
            name='pack',
            field=models.OneToOneField(blank=True, help_text='Pack dont la clé physique a été consommée. NULL si annulé/expiré (pack libéré).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_request', to='packs.packpurchase'),
        ),
    ]
