# Generated by Django 5.2.7 on 2026-02-17 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='checkout_url',
            field=models.URLField(blank=True, default='', help_text='URL de la page de paiement hébergée par le provider.', max_length=512, verbose_name='URL de paiement'),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider_tx_id',
            field=models.CharField(blank=True, default='', help_text='Identifiant de la transaction chez le provider externe.', max_length=255, verbose_name='ID transaction provider'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pack',
            field=models.OneToOneField(blank=True, help_text='Créé automatiquement après paiement confirmé.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='packs.packpurchase'),
        ),
    ]
