# Generated by Django 5.2.7 on 2026-03-27 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_provider_agnostic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('PAYSTACK', 'Paystack'), ('ORANGE_MONEY', 'Orange Money'), ('WAVE', 'Wave'), ('MTN', 'MTN Money'), ('CARD', 'Carte bancaire'), ('OTHER', 'Autre')], max_length=16, verbose_name='Fournisseur'),
        ),
    ]
